package DMTBSAPP;


/**
* DMTBSAPP/Cinema.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

public interface Cinema extends CinemaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cinema
