package DMTBSAPP;


/**
* DMTBSAPP/CinemaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

public interface CinemaOperations 
{

  // Define the function that returns the map
  DMTBSAPP.CinemaPackage.TicketInfo[] listMovieShowAvailability (String movieName);
  boolean removeMovieSlots (String movieID, String movieName);
  boolean addMovieSlots (String movieID, String movieName, int bookingCapacity);

  //Client Operations
  boolean cancelMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  String[] getBookingSchedule (String customerID);
  boolean bookMovieTickets (String customerID, String movieID, String movieName, int numberOfTickets);
  boolean exchangeTickets (String customerID, String movieID, String new_movieID, String new_movieName, int numberOfTickets);

  //create and write to files
  void createFile (String servername);
  void writeToFile (String message, String servername);
} // interface CinemaOperations
