package DMTBSAPP;


/**
* DMTBSAPP/CinemaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

public abstract class CinemaPOA extends org.omg.PortableServer.Servant
 implements DMTBSAPP.CinemaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("listMovieShowAvailability", new java.lang.Integer (0));
    _methods.put ("removeMovieSlots", new java.lang.Integer (1));
    _methods.put ("addMovieSlots", new java.lang.Integer (2));
    _methods.put ("cancelMovieTickets", new java.lang.Integer (3));
    _methods.put ("getBookingSchedule", new java.lang.Integer (4));
    _methods.put ("bookMovieTickets", new java.lang.Integer (5));
    _methods.put ("exchangeTickets", new java.lang.Integer (6));
    _methods.put ("createFile", new java.lang.Integer (7));
    _methods.put ("writeToFile", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Define the function that returns the map
       case 0:  // DMTBSAPP/Cinema/listMovieShowAvailability
       {
         String movieName = in.read_string ();
         DMTBSAPP.CinemaPackage.TicketInfo $result[] = null;
         $result = this.listMovieShowAvailability (movieName);
         out = $rh.createReply();
         DMTBSAPP.CinemaPackage.TicketMapHelper.write (out, $result);
         break;
       }

       case 1:  // DMTBSAPP/Cinema/removeMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         boolean $result = false;
         $result = this.removeMovieSlots (movieID, movieName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // DMTBSAPP/Cinema/addMovieSlots
       {
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int bookingCapacity = in.read_long ();
         boolean $result = false;
         $result = this.addMovieSlots (movieID, movieName, bookingCapacity);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  //Client Operations
       case 3:  // DMTBSAPP/Cinema/cancelMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         boolean $result = false;
         $result = this.cancelMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // DMTBSAPP/Cinema/getBookingSchedule
       {
         String customerID = in.read_string ();
         String $result[] = null;
         $result = this.getBookingSchedule (customerID);
         out = $rh.createReply();
         DMTBSAPP.CinemaPackage.StringSeqHelper.write (out, $result);
         break;
       }

       case 5:  // DMTBSAPP/Cinema/bookMovieTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         boolean $result = false;
         $result = this.bookMovieTickets (customerID, movieID, movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 6:  // DMTBSAPP/Cinema/exchangeTickets
       {
         String customerID = in.read_string ();
         String movieID = in.read_string ();
         String new_movieID = in.read_string ();
         String new_movieName = in.read_string ();
         int numberOfTickets = in.read_long ();
         boolean $result = false;
         $result = this.exchangeTickets (customerID, movieID, new_movieID, new_movieName, numberOfTickets);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }


  //create and write to files
       case 7:  // DMTBSAPP/Cinema/createFile
       {
         String servername = in.read_string ();
         this.createFile (servername);
         out = $rh.createReply();
         break;
       }

       case 8:  // DMTBSAPP/Cinema/writeToFile
       {
         String message = in.read_string ();
         String servername = in.read_string ();
         this.writeToFile (message, servername);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DMTBSAPP/Cinema:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cinema _this() 
  {
    return CinemaHelper.narrow(
    super._this_object());
  }

  public Cinema _this(org.omg.CORBA.ORB orb) 
  {
    return CinemaHelper.narrow(
    super._this_object(orb));
  }


} // class CinemaPOA
