package DMTBSAPP.CinemaPackage;


/**
* DMTBSAPP/CinemaPackage/TicketMapHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/


// Define the map type that will be returned by the function
public final class TicketMapHolder implements org.omg.CORBA.portable.Streamable
{
  public DMTBSAPP.CinemaPackage.TicketInfo value[] = null;

  public TicketMapHolder ()
  {
  }

  public TicketMapHolder (DMTBSAPP.CinemaPackage.TicketInfo[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DMTBSAPP.CinemaPackage.TicketMapHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DMTBSAPP.CinemaPackage.TicketMapHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DMTBSAPP.CinemaPackage.TicketMapHelper.type ();
  }

}
