package DMTBSAPP.CinemaPackage;


/**
* DMTBSAPP/CinemaPackage/TicketMapHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/


// Define the map type that will be returned by the function
abstract public class TicketMapHelper
{
  private static String  _id = "IDL:DMTBSAPP/Cinema/TicketMap:1.0";

  public static void insert (org.omg.CORBA.Any a, DMTBSAPP.CinemaPackage.TicketInfo[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DMTBSAPP.CinemaPackage.TicketInfo[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = DMTBSAPP.CinemaPackage.TicketInfoHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (DMTBSAPP.CinemaPackage.TicketMapHelper.id (), "TicketMap", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DMTBSAPP.CinemaPackage.TicketInfo[] read (org.omg.CORBA.portable.InputStream istream)
  {
    DMTBSAPP.CinemaPackage.TicketInfo value[] = null;
    int _len0 = istream.read_long ();
    value = new DMTBSAPP.CinemaPackage.TicketInfo[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = DMTBSAPP.CinemaPackage.TicketInfoHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DMTBSAPP.CinemaPackage.TicketInfo[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      DMTBSAPP.CinemaPackage.TicketInfoHelper.write (ostream, value[_i0]);
  }

}
