package DMTBSAPP.CinemaPackage;

/**
* DMTBSAPP/CinemaPackage/TicketInfoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

public final class TicketInfoHolder implements org.omg.CORBA.portable.Streamable
{
  public DMTBSAPP.CinemaPackage.TicketInfo value = null;

  public TicketInfoHolder ()
  {
  }

  public TicketInfoHolder (DMTBSAPP.CinemaPackage.TicketInfo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DMTBSAPP.CinemaPackage.TicketInfoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DMTBSAPP.CinemaPackage.TicketInfoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DMTBSAPP.CinemaPackage.TicketInfoHelper.type ();
  }

}
