package DMTBSAPP.CinemaPackage;


/**
* DMTBSAPP/CinemaPackage/TicketInfoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

abstract public class TicketInfoHelper
{
  private static String  _id = "IDL:DMTBSAPP/Cinema/TicketInfo:1.0";

  public static void insert (org.omg.CORBA.Any a, DMTBSAPP.CinemaPackage.TicketInfo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DMTBSAPP.CinemaPackage.TicketInfo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "movieName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "capacity",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (DMTBSAPP.CinemaPackage.TicketInfoHelper.id (), "TicketInfo", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DMTBSAPP.CinemaPackage.TicketInfo read (org.omg.CORBA.portable.InputStream istream)
  {
    DMTBSAPP.CinemaPackage.TicketInfo value = new DMTBSAPP.CinemaPackage.TicketInfo ();
    value.movieName = istream.read_string ();
    value.capacity = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DMTBSAPP.CinemaPackage.TicketInfo value)
  {
    ostream.write_string (value.movieName);
    ostream.write_long (value.capacity);
  }

}
