package DMTBSAPP.CinemaPackage;


/**
* DMTBSAPP/CinemaPackage/TicketInfo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DMTBS.idl
* Sunday, February 19, 2023 8:49:09 PM EST
*/

public final class TicketInfo implements org.omg.CORBA.portable.IDLEntity
{
  public String movieName = null;
  public int capacity = (int)0;

  public TicketInfo ()
  {
  } // ctor

  public TicketInfo (String _movieName, int _capacity)
  {
    movieName = _movieName;
    capacity = _capacity;
  } // ctor

} // class TicketInfo
